"""add genres and movie_genres

Revision ID: 20c279bf3a41
Revises: 5250da33359f
Create Date: 2026-07-29 16:31:35.557602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c279bf3a41'
down_revision: Union[str, Sequence[str], None] = '5250da33359f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdb_id')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profile_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdb_id')
    )
    op.create_table('movie_cast',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('character', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'person_id')
    )
    op.create_table('movie_crew',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'person_id', 'job')
    )
    op.create_table('movie_genres',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    op.add_column('movies', sa.Column('tmdb_id', sa.Integer(), nullable=False))
    op.add_column('movies', sa.Column('adult', sa.Boolean(), nullable=False))
    op.add_column('movies', sa.Column('original_language', sa.String(length=10), nullable=False))
    op.add_column('movies', sa.Column('overview', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('tagline', sa.Text(), nullable=True))
    op.add_column('movies', sa.Column('release_date', sa.Date(), nullable=True))
    op.add_column('movies', sa.Column('runtime', sa.Integer(), nullable=True))
    op.add_column('movies', sa.Column('poster_path', sa.String(), nullable=True))
    op.add_column('movies', sa.Column('backdrop_path', sa.String(), nullable=True))
    op.create_index(op.f('ix_movies_tmdb_id'), 'movies', ['tmdb_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_tmdb_id'), table_name='movies')
    op.drop_column('movies', 'backdrop_path')
    op.drop_column('movies', 'poster_path')
    op.drop_column('movies', 'runtime')
    op.drop_column('movies', 'release_date')
    op.drop_column('movies', 'tagline')
    op.drop_column('movies', 'overview')
    op.drop_column('movies', 'original_language')
    op.drop_column('movies', 'adult')
    op.drop_column('movies', 'tmdb_id')
    op.drop_table('movie_genres')
    op.drop_table('movie_crew')
    op.drop_table('movie_cast')
    op.drop_table('people')
    op.drop_table('genres')
    # ### end Alembic commands ###
